### ISSUE TITLE
wallet : notifications non attendues

### ISSUE THREAD

**Issue by n0uki63** [archethic-foundation/bug-bounty#1]
### Description

Dans le wallet, j'ai créé 3 comptes.

J'ai envoyé des ucos sur les différents comptes par le faucet.

Lorsque je navigue dans l'application en passant d'un compte à l'autre, je continue à recevoir les notifications des ucos précédemment reçus de manière intempestive.

### Platform

Android

### Version of Archethic apps

1.0.0 DayOne

**Comment by monkeycraz** [comment]
Meme pb !
G également des notifications sonores qui continuent d etre actuve malgré leur mise en sourdine

**Comment by n0uki63** [comment]
La mise en sourdine des notifications est un autre problème qui a déjà fait l'objet de l'enregistrement d'une issue dans les versions testnet

**Comment by redDwarf03** [comment]
Thank @n0uki63 for your feedback. This issue is known in issue https://github.com/archethic-foundation/archethic-wallet/issues/182

but, i should precise the issue about sound is not declared in an issue.
