### ISSUE TITLE
[Explorer]: Crash (Internal Error) on the transaction detail page 

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/bug-bounty#18]
### Description

I uploaded a few contents in the following chain

https://mainnet.archethic.net/explorer/chain?address=0100b1b5bbb1e0d22121b69dff071b2e256cc99607a380e45f12f71f59cbb3e3a884

If you click on a transaction such as (0100E34EF74EF4BDA086917872CC8FE843508CBFDE63B04C11A2825BFFA501764159)[https://mainnet.archethic.net/explorer/transaction/0100E34EF74EF4BDA086917872CC8FE843508CBFDE63B04C11A2825BFFA501764159]

You have a page "Internal Server Error"

However, if you call the link for displaying the page, it is fine
https://mainnet.archethic.net/api/last_transaction/0100E34EF74EF4BDA086917872CC8FE843508CBFDE63B04C11A2825BFFA501764159/content?mime=text/html

### Fix

I think it is something with the content that cause the crash

**Comment by Neylix** [comment]
Hello,
Thanks for reporting this bug. I created a new issue for it : https://github.com/archethic-foundation/archethic-node/issues/457
