### ISSUE TITLE
[Improvement]: AEWEB missing error message "not enought funds"

### ISSUE THREAD

**Issue by Alexrollo64** [archethic-foundation/bug-bounty#19]
### Description

When i try to upload a html file on aeweb with mainnet on endpoint , with a **wallet of 0 uco** , it's just waiting and nothing appear to prevent you **that the wallet needs funds :**

It's waiting there for like 20 minutes now , **it needs an error message and stopping the transaction.**

### Logs / Images

-- IMPROVEMENT --

Creating file structure and compress content...
Spliting file(s) content in multiple transaction if necessary ...
Creating transactions, it may take a while...
Estimating fees...
Total Fee Requirement would be : 2.33 UCO ( $ 0.23 | € 0.23), for 3 transactions.
Do you want to continue. (yes/no) y
Sending 3 transactions...
Transaction 1...
Waiting transaction validation...

### Platform

Windows 10 

### Version of Archethic apps

the most recent aeweb 

### Fix

**it needs an error message and stopping the transaction.**

**Comment by Neylix** [comment]
Hello,
The problem is that actually the transaction subscriber do not return errors during validation but only when a transaction is validated.
There is already an issue to cover this functionnality : https://github.com/archethic-foundation/archethic-node/issues/445
