### ISSUE TITLE
wallet : ajout de compte avec certains caractères spéciaux

### ISSUE THREAD

**Issue by n0uki63** [archethic-foundation/bug-bounty#2]
### Description

Lors de l'ajout d'un compte avec un nom contenant certains caractères spéciaux comme le "point médian", l'application tente de le créer.

Plusieurs réactions constatées : 
- l'application revient à la liste et le compte n'est pas créé
- le nom s'affiche dans la liste, mais l'indicateur "veuillez patienter" boucle sans fin
- le nom s'affiche correctement sans que ca boucle, mais le compte est inaccessible. En switchant de compte et en rappelant la liste, ce dernier disparait

De manière aléatoire, le bouton OK de validation du nom devient "gris" et il n'est même plus possible de créer un compte avec un nom valide. Pour rétablir la situation, il faut alors fermer complétement l'app et la réouvrir.

### Platform

Android

### Version of Archethic apps

1.0.0 DayOne

**Comment by redDwarf03** [comment]
This issue has been fixed. it will be available in next version 1.0.4. You could review this issue when the version will be published

**Comment by redDwarf03** [comment]
Hello @n0uki63, could you try with the lastest version (1.0.6) available on google store or apple store please

**Comment by redDwarf03** [comment]
Closing the case without review of the author.
