### ISSUE TITLE
[Bug]: import secret phrase with error

### ISSUE THREAD

**Issue by kgricour** [archethic-foundation/bug-bounty#22]
### Description

Après importation d'une secret phrase de 24 mots valides en fonction de la norme bip39 mais qui n'existe pas dans la keychain (ex: inversion de deux mot dans la secret phrase), au moment de la validation il ne se passe strictement rien et le message d'erreur 'No keychain exists with this secret phrase.' ne s'affiche donc pas. 

Ce message d'erreur s'affiche dans les logs : 

Suite à ça en essayant de  remettre la secret phrase correct, la validation est également impossible. 

### Logs / Images

`Uncaught (in promise) Error: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:251:49)
    at Object.nullCheck (operations.dart:528:63)
    at intro_import_seed._IntroImportSeedState.new.<anonymous> (intro_import_seed.dart:442:52)
    ...
`

### Platform

Android

### Version of Archethic apps

1.0.0

### Fix

Dand le fichier `archethic-wallet/packages/aeuniverse/lib/ui/views/intro/intro_import_seed.dart`  ligne 438 :  

mettre : 
`appWallet?.appKeychain!.accounts;`

au lieu de : 
`appWallet!.appKeychain!.accounts;`

**Comment by redDwarf03** [comment]
Hello. Thx for your feedback. Yes, This issue has been detected and fixed in this issue: https://github.com/archethic-foundation/archethic-wallet/issues/190. The next version 1.0.1 will integrate a fix about this.

**Comment by kgricour** [comment]
Salut, j'ai peut être pas été clair dans mes explications mais le problème n'est pas le même que l'issue https://github.com/archethic-foundation/archethic-wallet/issues/190  car dans l'issue 190 le compte est trouvé dans la Keychain mais pas dans le cas de mon issue.

**Comment by redDwarf03** [comment]
ok. could you send me the 24 words please

**Comment by kgricour** [comment]
Tu peux essayer avec ces 24 mots la @redDwarf03  : 
mean cactus stick shine snow elevator aspect dune dignity cricket steel exercise level avocado upgrade side cram simple boost grunt picture trouble stone chicken

**Comment by redDwarf03** [comment]
ok. i see the pb. thx

**Comment by redDwarf03** [comment]
@kgricour could you do a review with 1.0.1 to confirm this issue is fixed following your feedback. Thx

**Comment by kgricour** [comment]
Salut @redDwarf03 non ce n'est pas ok, le message "no keychain exists with this secret phrase"  s'affiche désormais dans tout les cas( avec un compte existant dans la keychain ou non)

**Comment by redDwarf03** [comment]
warning. like precise in telegram: "A major update that improves the stability of our ecosystem is available now.
The version (v1.0.2) of the Archethic wallet available on https://archethic.net/aewallet.html is required. 
Each user must recreate his wallet & retrieve UCO's in the Faucet."
So, since yesterday, all keychains are removed. Sorry for that

**Comment by kgricour** [comment]
Okay, sorry, I didn't see that information. Everything is OK for me then.
