### ISSUE TITLE
Wallet : Journal des transactions recentes

### ISSUE THREAD

**Issue by monkeycraz** [archethic-foundation/bug-bounty#23]
### Description

Si ma dernière transaction est un - retrait d uco, 
il me retire de l écran les + debit 
pour ne laissez que les retrait rouge
( qui étaient moins recent ) 

### Logs / Images

#
![Screenshot_20220717-102704](https://user-images.githubusercontent.com/99678101/179391044-02743fee-af6e-403d-b25f-22178a1c733e.jpg)
![Screenshot_20220717-102801](https://user-images.githubusercontent.com/99678101/179391045-3eb576a2-82d2-4d25-b11b-93442cc8d112.jpg)

**Comment by redDwarf03** [comment]
@monkeycraz could you do a review with 1.0.1 to confirm this issue is fixed following your feedback. Thx

**Comment by monkeycraz** [comment]
@redDwarf03 
Bjr, le pb est bien résolu avec la mise à jour de la version 1.0.1 ! Merci .
