### ISSUE TITLE
wallet : transactions à 0 uco

### ISSUE THREAD

**Issue by n0uki63** [archethic-foundation/bug-bounty#25]
### Description

La tentative d'une transaction de 0 uco entraîne une boucle lors de la confirmation de la transaction.

### Platform

Android

### Version of Archethic apps

1.0.2

### Fix

Il faudrait bloquer l'action au moment de la tentative d'envoi.

Même comportement que lorsque l'on tente d'envoyer à l'adresse du portefeuille ou si mauvaise keychain renseignée

**Comment by redDwarf03** [comment]
https://github.com/archethic-foundation/archethic-wallet/issues/219
