### ISSUE TITLE
wallet : impossible de créer plus de 6 comptes

### ISSUE THREAD

**Issue by n0uki63** [archethic-foundation/bug-bounty#3]
### Description

Il semble impossible de créer + de 6 comptes dans 1 wallet.

### Platform

Android

### Version of Archethic apps

1.0.0 DayOne

**Comment by n0uki63** [comment]
Je peux à-nouveaux créer des comptes au delà de 6 après suppression et réimport du wallet

**Comment by monkeycraz** [comment]
Chez moi g pu en ajouter 11, mais effectivement au bout du 6 ieme g du ressortir puis  rerentrer sur l interface compte pour que cela soit affiché !

**Comment by n0uki63** [comment]
Je vais refaire un test sur le sujet avec un nouveau wallet

**Comment by redDwarf03** [comment]
hello. i can't reproduce the issue. Sorry. Could you retry ?

**Comment by redDwarf03** [comment]
@n0uki63 , @monkeycraz could you do a review with 1.0.1 to confirm this issue is fixed following your feedback. Thx (without special characters 😉)

**Comment by monkeycraz** [comment]
@redDwarf03 Bjr, je ne rencontre plus ce pb de mon côté !
Ayant crée un new wallet et 10 comptes sans caractère spéciaux 😇
Par contre sur ce nvo wallet je n arrive quasiment jamais a swapper de compte il revient 4x/5 sur le compte précédent !

**Comment by redDwarf03** [comment]
yes, the problem is known. you have to wait a few seconds for some background tasks to finish before you can change your account. The problem will be solved in the next version
