### ISSUE TITLE
[Bug]: Loading without timeout

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/bug-bounty#33]
### Description

See: https://github.com/archethic-foundation/archethic-wallet/issues/209
Author: @LucBerge

**Comment by LucBerge** [comment]
With the version 1.0.4 I have the following error:
`PhoenixException: socket closed`

The timeout issue is solved. Should I open a new issue with this exception ?

**Comment by redDwarf03** [comment]
hello. Thanks for the message. 1.0.4 is actually in pre release. We don't communicate about this vesion officially because we are testing actually the wallet and the node before official diffusion. 
I let this issue open because we have to see together if it works after internal tests.
Thank again for your feedbacks

**Comment by redDwarf03** [comment]
Hello @LucBerge , could you try with the lastest version (1.0.6) available on google store or apple store please

**Comment by LucBerge** [comment]
Same issue with the version 1.0.6

**Comment by redDwarf03** [comment]
the issue comes from old versions of Android (<= 7.0) with error: ```CERTIFICATE_VERIFY_FAILED: certificate has expired```

**Comment by redDwarf03** [comment]
@LucBerge , what about the 2.0.6 ? thx

**Comment by LucBerge** [comment]
Working ! Thank you for the job !
