### ISSUE TITLE
[Bug]: Modification des informations d'un contact

### ISSUE THREAD

**Issue by ElNelyo** [archethic-foundation/bug-bounty#36]
### Description

J'ai crée un nouveau contact dans mon carnet d'adresse.
Cependant si je me trompe du nom/adresse il n'est pas possible de le modifier. Il faut donc le supprimer et recréer un contact

### Logs / Images

<img width="396" alt="Capture d’écran 2022-08-07 à 18 36 22" src="https://user-images.githubusercontent.com/17676307/183301520-f1493659-1701-43cc-99cd-db188a1d1a7f.png">

### Platform

MacOS

### Version of Archethic apps

1_03

### Fix

Pouvoir modifier "en live" les informations du contact et enregistrer ce dernier.

**Comment by redDwarf03** [comment]
Hello. your feedbacks are pertinent and your tests are good. Thx! but don't forget to see before open issues in the wallet repo :)
https://github.com/archethic-foundation/archethic-wallet/issues?q=is%3Aopen+is%3Aissue

this issue exists: https://github.com/archethic-foundation/archethic-wallet/issues/70

**Comment by ElNelyo** [comment]
Ohhh yes my bad,
Sorry i thought it was fixed, i'll look at it before sending any issues !
