### ISSUE TITLE
[Bug]: Voir dans l'explorer

### ISSUE THREAD

**Issue by ElNelyo** [archethic-foundation/bug-bounty#37]
### Description

Le bouton voir dans l'explorer renvois vers la page d'une transaction
Ce n'est pas forcément très explicite pour l'utilisateur.

### Logs / Images

<img width="392" alt="Capture d’écran 2022-08-07 à 18 49 17" src="https://user-images.githubusercontent.com/17676307/183360778-3b936d39-a78c-4a82-8e9d-f15f286faedd.png">

### Platform

MacOs

### Version of Archethic apps

1_03

### Fix

Chemin actuel 
https://testnet.archethic.net/explorer/transaction/00008b829165654cc91b6ae9aa23468c58ff8a1caf67de820bc0db72ef5b5944f77d
Chemin proposé 
https://testnet.archethic.net/explorer/chain?address=00005B7B6F28C767B2AA5555674B414116EBC699A886EC742BAD9EBD272BB73DBC5E&last=on

**Comment by samuel-uniris** [comment]
Bonjour, merci de votre contribution.
Cependant, j'ai du mal à saisir la portée de votre retour.
En plus l'image semble ne pas fonctionner.
Pourriez-vous nous donner plus d'explications ?
Merci

**Comment by ElNelyo** [comment]
Bonjour Samuel,
Effectivement l'image ne s'affiche pas de mon côté également.. je vais essayer de le remplacer.

Le bouton "Voir dans l'explorer" me renvois vers une page vide en indiquant "The transaction does not exists yet." cependant j'ai déjà fait 2-3 appels du faucets.. 

Comme on peut le voir https://testnet.archethic.net/explorer/chain?address=00005B7B6F28C767B2AA5555674B414116EBC699A886EC742BAD9EBD272BB73DBC5E&last=on

Il y a quelque chose de pas clair pour l'utilisateur.

Je vous remercie

**Comment by samuel-uniris** [comment]
La chose est que je ne vois pas le lien entre l'adresse : 00005B7B6F28C767B2AA5555674B414116EBC699A886EC742BAD9EBD272BB73DBC5E et 00008b829165654cc91b6ae9aa23468c58ff8a1caf67de820bc0db72ef5b5944f77d .

Si l'on cherche la transaction 00005B7B6F28C767B2AA5555674B414116EBC699A886EC742BAD9EBD272BB73DBC5E on obtient bien le détail de la transaction

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/42943690/183362330-23ad20c3-5cb7-4e8e-864f-46c8efaff0c6.png">

**Comment by ElNelyo** [comment]
Le lien que je vous envois provient directement de "Voir l'explorer"

**Comment by samuel-uniris** [comment]
Il semble que les fonds ont été envoyé sur la keychain (00005B7B6F28C767B2AA5555674B414116EBC699A886EC742BAD9EBD272BB73DBC5E ) au lieu du compte UCO (00008b829165654cc91b6ae9aa23468c58ff8a1caf67de820bc0db72ef5b5944f77d)

**Comment by ElNelyo** [comment]
Je comprends mieux la confusion, j'ai testé avec le compte UCO cela à l'air de mieux fonctionner.
Désolé certainement une mauvaise manipulation de mon côté

**Comment by samuel-uniris** [comment]
Ok, je ferme l'issue donc
