### ISSUE TITLE
[Bug]: Liens à Propos ne fonctionnent pas

### ISSUE THREAD

**Issue by ElNelyo** [archethic-foundation/bug-bounty#38]
### Description

Les liens "Conditions générales" et "Condition d'utilisation du portefeuille" ne redirige pas vers la bonne adresse

### Logs / Images

<img width="389" alt="Capture d’écran 2022-08-07 à 18 53 05" src="https://user-images.githubusercontent.com/17676307/183302159-ea5d9b0a-326e-466d-aee0-2fee3b04f778.png">

### Platform

MacOS

### Version of Archethic apps

1_03

### Fix

Rediriger vers les pages correspondantes

**Comment by redDwarf03** [comment]
Hello. Thank you (again :)) for your feedbacks.
You're right. We are writing actually these texts but we actually prioritize features and fix bugs.  
I'm sorry but this issue is out of scope of bug bounty

**Comment by redDwarf03** [comment]
we had open issues : 
https://github.com/archethic-foundation/archethic-wallet/issues/92
https://github.com/archethic-foundation/archethic-wallet/issues/91
https://github.com/archethic-foundation/archethic-wallet/issues/90

**Comment by ElNelyo** [comment]
Hi :)

No problem ! 
I noted what I saw missing but actually it is not a bug in itself.
If I'm ever too precise (and boring) don't hesitate to tell me

**Comment by redDwarf03** [comment]
you are perfect :) your feebacks are important. So thank you for that
