### ISSUE TITLE
[Bug]: Problème d'UI

### ISSUE THREAD

**Issue by ElNelyo** [archethic-foundation/bug-bounty#39]
### Description

Quand je veux regarder l'historique du prix de l'UCO en devise BTC Bitcoin,
L'UI de la page n'est pas correcte.

### Logs / Images

<img width="393" alt="Capture d’écran 2022-08-08 à 09 20 08" src="https://user-images.githubusercontent.com/17676307/183362066-3951c5bb-fa89-4cc8-820e-c44705a60480.png">

### Platform

MacOS

### Version of Archethic apps

1_03

### Fix

Réduire un peu le texte et l'espacer d'avantage

**Comment by redDwarf03** [comment]
Hello.
Thank you for your feedbacks. We had identify this issue in the https://github.com/archethic-foundation/archethic-wallet/issues/181
