### ISSUE TITLE
[Bug]: transaction freeze indefiniment !

### ISSUE THREAD

**Issue by monkeycraz** [archethic-foundation/bug-bounty#4]
### Description

Lors de l envoi d'UCO en incluant certain caracteres spéciaux comme l euro "€"  ds le msg, la transaction mouline indéfiniment avec l indicateur " veuillez patientez" sans valider la transaction ! 
A l inverse du sigle $ qui lui n empeche pas la transaction de s effectuer normalement .

**Comment by redDwarf03** [comment]
Thank you @monkeycraz. Like @n0uki63 said, this issue is known and declared in this issue: https://github.com/archethic-foundation/archethic-wallet/issues/188
