### ISSUE TITLE
[Bug]: claim uco wallet

### ISSUE THREAD

**Issue by Sebdens** [archethic-foundation/bug-bounty#42]
### Description

hello, 
first I congratulate you on the launch of the mainnet.
I'm not familiar with github.
I am only a simple user and I have just created my account to send you a "bug" concerning the wallet.
It is stated that we can claim 10 UCO per 24h.  Only after deleting and reinstalling the wallet to test my recovery phrase, I was able to claim 10 UCO again.
It is therefore possible to empty the pool of 10,000 UCO by deleting and reinstalling the application several times a day with the same wallet.  I hope this has helped you.
I apologize for my English, i'm French and I don't know if I should write here in French or English.
Sébastien 

### Version of Archethic apps

Wallet

**Comment by redDwarf03** [comment]
Thank you for your message and feeback.
