### ISSUE TITLE
[Bug]: Copy doesn't work on Explorer

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/bug-bounty#44]
### Description

On this link : /explorer/transaction/0000AC5E54C3DCFFCDE02DBA3A82A10406CB5FFA89DC053E778B4511B4EBEB426EFE

The copy link on the content, didn't copy correctly the content

**Comment by samuelmanzanera** [comment]
Thanks for the contribution.
But this is already known and reporter by the team (https://github.com/archethic-foundation/archethic-node/issues/758)
