### ISSUE TITLE
[Bug]: OKX wallet - uco - ETH>ARCH

### ISSUE THREAD

**Issue by RVe74** [archethic-foundation/bug-bounty#49]
### Description

Report on discord : 15/10/2023 00:13
Use wallet OKX
Send Uco from sepolia ethereum testnet to archethic testnet
Bug : formatexception 

### Logs / Images

![6bfc1b1b-3dec-4605-a18a-3f849ce30446](https://github.com/archethic-foundation/bug-bounty/assets/150965024/86e25827-cf3f-4dd8-970d-43be2ab2f17c)

### Platform

Windows 

### Version of Archethic's wallet

2.3.1

### Version of Archethic's Bridge

0.0.9

### EVM wallet

OkX

**Comment by redDwarf03** [comment]
Hello
Thank you for your contribution.
This issue concerns the EVM wallet compatibility. 
You can follow the advancement of Archethic team’s tests in this issue: https://github.com/archethic-foundation/bridge/issues/10

The OKS wallet has not yet been fully tested, so we thank you for your feedback. 
Compliance development has begun.
