### ISSUE TITLE
wallet : liste non actualisée lors de la suppression d'un contact

### ISSUE THREAD

**Issue by n0uki63** [archethic-foundation/bug-bounty#5]
### Description

Lors de l'ajout d'un contact dans le carnet d'adresse, ce dernier apparait dans la liste après validation.

Lors de la suppression d'un contact, la liste n'est pas rafraichie dynamiquement comme à l'ajout.

Il convient de quitter l'écran et de retourner dans le carnet d'adresse pour visualiser que la suppression est effective.

### Platform

Android

### Version of Archethic apps

1.0.0 DayOne

### Fix

[non prioritaire]

**Comment by redDwarf03** [comment]
Thank you @n0uki63. We will add this issue in the wallet’s backlog

**Comment by redDwarf03** [comment]
@n0uki63 could you do a review with 1.0.1 to confirm this issue is fixed following your feedback. Thx

**Comment by n0uki63** [comment]
Problème résolu dans la version 1.0.1
