### ISSUE TITLE
[Bug]: SafePad wallet  - uco - ARCH>ETH

### ISSUE THREAD

**Issue by RVe74** [archethic-foundation/bug-bounty#55]
### Description

safePad wallet
Send uco from Archethic testnet to sepolia ethereum testnet 
I can't validate the transaction due to lack of feeds ( no fee proposal )

### Logs / Images

![image](https://github.com/archethic-foundation/bug-bounty/assets/150965024/64b064b6-d2db-49b4-9cb7-96ec15261574)

{
  "resumeProcess": false,
  "bridgeProcessStep": "confirmation",
  "blockchainFrom": {
    "name": "Archethic Testnet",
    "chainId": -2,
    "env": "2-testnet",
    "icon": "Archethic.svg",
    "urlExplorerAddress": "https://testnet.archethic.net/explorer/transaction/",
    "urlExplorerTransaction": "https://testnet.archethic.net/explorer/transaction/",
    "providerEndpoint": "",
    "isArchethic": true,
    "nativeCurrency": "UCO",
    "htlcAddress": "0000fc8e8e3dba63aeb80ef106ee2650c87bcda07f7da47de422a65f4da27a024d78",
    "archethicFactoryAddress": "0000795bfd6ca2f5ea9f378c20775caf798e9bfbff6aec94bf87ad8d59233b4fa299"
  },
  "blockchainTo": {
    "name": "Sepolia Ethereum Testnet",
    "chainId": 11155111,
    "env": "2-testnet",
    "icon": "Ethereum.svg",
    "urlExplorerAddress": "https://sepolia.etherscan.io/address/",
    "urlExplorerTransaction": "https://sepolia.etherscan.io/tx/",
    "providerEndpoint": "https://sepolia.infura.io/v3/3a7a2dbdbec046a4961550ddf8c7d78a",
    "isArchethic": false,
    "nativeCurrency": "ETH",
    "htlcAddress": null,
    "archethicFactoryAddress": null
  },
  "tokenToBridge": {
    "name": "Universal Coin",
    "tokenAddressSource": "",
    "tokenAddressTarget": "0xCBBd3374090113732393DAE1433Bc14E5233d5d7",
    "symbol": "UCO",
    "targetTokenName": "ERC20 - Universal Coin",
    "targetTokenSymbol": "UCO",
    "poolAddressFrom": "000018d60115ece0c7558a46b4693749bf6beab524fddccf9b10b910619e4ee08801",
    "poolAddressTo": "0x50b8B73327613468e5605eD59B980555DAAC354a",
    "type": "Native"
  },
  "tokenToBridgeAmount": 50,
  "targetAddress": "0xb6d20ab2aca7a331de5f67ab5cfc70b4a83a96ff",
  "tokenToBridgeBalance": 184.39229674,
  "tokenBridgedBalance": 0,
  "poolTargetBalance": 200181.09874041856,
  "tokenToBridgeDecimals": 8,
  "failure": {
    "runtimeType": "userRejected"
  },
  "isTransferInProgress": true,
  "walletConfirmation": "evm",
  "currentStep": 4,
  "changeDirectionInProgress": false,
  "timestampExec": 1700635418851,
  "archethicOracleUCO": null,
  "htlcAEAddress": "0000fc8e8e3dba63aeb80ef106ee2650c87bcda07f7da47de422a65f4da27a024d78",
  "htlcEVMAddress": null,
  "htlcEVMTxAddress": null,
  "secret": null,
  "safetyModuleFeesRate": 0,
  "safetyModuleFeesAddress": "",
  "archethicProtocolFeesRate": 0.3,
  "archethicProtocolFeesAddress": "0000749D250560BF06C079832E0E9A24509B1E440A45C33BD9448B41B6A056FC6201",
  "archethicTransactionFees": 0
}

### Platform

windows

### Version of Archethic's wallet

2.3.1 476

### Version of Archethic's Bridge

0.0.9 11

### EVM wallet

SafePad

**Comment by redDwarf03** [comment]
I create an issue on SafePal support: #192089

**Comment by redDwarf03** [comment]
No answer from SafePal...
This issue is not related to aeBridge but directly from EVM Wallet
