### ISSUE TITLE
wallet : rafraichissement du solde du wallet en devise lors d'un changement de devise

### ISSUE THREAD

**Issue by n0uki63** [archethic-foundation/bug-bounty#7]
### Description

Lorsque d'un changement de devise dans les préférences, passage de € à btc par exemple, la valorisation du wallet en devise n'est pas actualisée automatiquement.

### Platform

Android

### Version of Archethic apps

1.0.0 DayOne

### Fix

Exécuter un refresh de l'interface après sélection de la nouvelle devise

**Comment by redDwarf03** [comment]
Thx. we will add this issue in the backlog.

**Comment by redDwarf03** [comment]
@n0uki63 could you do a review with 1.0.1 to confirm this issue is fixed following your feedback. Thx
